//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice_empty_c_mvc_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artist
    {
        public int art_id { get; set; }
        public int mus_gen_id { get; set; }
        public string art_code { get; set; }
        public string art_name { get; set; }
        public int art_status { get; set; }
    }
}
